spring:
    datasource:
        url: jdbc:postgresql://postgresql-svc.default:5432/project
        username: postgres
        password: hr
    jpa:
        show-sql: true
        open-in-view: false
        hibernate:
            ddl-auto: create-drop
    redis:
        host: redis-svc.default
        port: 6379


logging:
   level: 
       root: INFO

        